### ISSUE TITLE
As a gift recipient, I want to display my clothing and shoe sizes so that my friends can buy me gifts that fit me

### ISSUE THREAD

**Issue by FirasBDarwish** [software-students-spring2024/2-web-app-exercise-fizzbuzz#1]
# Tasks:

## Front-End:

- [ ] Use HTML and CSS to develop a front-end that showcases user's profile based on the Figma prototype designed.

## Back-End:
- [ ] Use Flask to create a back-end that stores user's clothing and shoe sizes to be displayed on the front-end
- [ ] Allow users to edit their clothing and shoe size, reflecting change in the mongodb databas
