### ISSUE TITLE
As a gift recipient, I want to add a new post to my interest board so that gift givers can buy me something I actually like

### ISSUE THREAD

**Issue by DoodyShark** [software-students-spring2024/2-web-app-exercise-fizzbuzz#15]
# Tasks

## Front-End
- [x] HTML and CSS for listing each image as a card

## Back-End
- [x] Add tpost button to add new post
- [x] Add that post to liked posts
