### ISSUE TITLE
As a new user, I want to register an account so that I can start using the application

### ISSUE THREAD

**Issue by DoodyShark** [software-students-spring2024/2-web-app-exercise-fizzbuzz#2]
# Tasks

## Front-End:
- [x]  Create template for registration (form to retrieve user-name, email, password, date of birth, etc.)

## Back-End:
- [x]  Handle GET request to view registration page
- [x]  Connect to MongoDB database to add new user
- [x]  Handle post request from register form to use it to populate the data in the database
