### ISSUE TITLE
As a gift recipient, I want to announce events so that I don't need to send individual invites

### ISSUE THREAD

**Issue by FirasBDarwish** [software-students-spring2024/2-web-app-exercise-fizzbuzz#4]
# Tasks:

## Front-End:

- [ ] Create template where gift recipients can announce events and invite mutual friends 

## Back-End:

- [ ] Linking gift-recipient event announcement page to button in gift-recipient profile page
- [ ] Update mongodb accordingly when event is announced
- [ ] Push event to the profiles of invited users
