### ISSUE TITLE
As a gift recipient, I want to add to my interest board from existing photos so that gift givers can buy me something I actually like

### ISSUE THREAD

**Issue by DoodyShark** [software-students-spring2024/2-web-app-exercise-fizzbuzz#9]
# Tasks

## Front-End
- [x] HTML and CSS for listing each image as a card

## Back-End
- [x] Fetch the photos
- [x] List them in For You page
- [x] Add to interests button to add image id
